/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "parse_q.h"
#include "bcf.h"
#include "off.h"
#include "wahbm.h"
#include "ubin.h"
#include "plt.h"
#include "genotq.h"
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <stdio.h>
#include <inttypes.h>
#include <string.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_init_bcf_file(void);
extern void test_get_bcf_line(void);
extern void test_push_bcf_gt_offset(void);
extern void test_push_bcf_gt_md(void);
extern void test_plt_line_to_packed_ints(void);
extern void test_ubin_to_bitmap_wah(void);
extern void test_convert_file_by_name_ubin_to_wahbm(void);


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  UnityBegin();
  Unity.TestFile = "test_genotq.c";
  RUN_TEST(test_init_bcf_file, 70);
  RUN_TEST(test_get_bcf_line, 85);
  RUN_TEST(test_push_bcf_gt_offset, 130);
  RUN_TEST(test_push_bcf_gt_md, 177);
  RUN_TEST(test_plt_line_to_packed_ints, 211);
  RUN_TEST(test_ubin_to_bitmap_wah, 288);
  RUN_TEST(test_convert_file_by_name_ubin_to_wahbm, 391);

  return (UnityEnd());
}
